#ifndef UBXROBOT3DVIEW_GLOBAL_H
#define UBXROBOT3DVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBXROBOT3DVIEW_LIBRARY)
#  define UBXROBOT3DVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBXROBOT3DVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBXROBOT3DVIEW_GLOBAL_H
