#ifndef UBXROBOTCONTROLLER_GLOBAL_H
#define UBXROBOTCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef UBXROBOTCONTROLLER_EXPORTS
#define UBXROBOTCONTROLLER_API Q_DECL_EXPORT
#else
#define UBXROBOTCONTROLLER_API Q_DECL_IMPORT
#endif

#endif // UBXROBOT3DVIEW_GLOBAL_H
