#ifndef UBXEVENTEDITOR_GLOBAL_H
#define UBXEVENTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBXEVENTEDITOR_LIBRARY)
#  define UBXEVENTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBXEVENTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBXEVENTEDITOR_GLOBAL_H
