#ifndef UBXSOCKETSESSION_GLOBAL_H
#define UBXSOCKETSESSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBXSOCKETSESSION_LIBRARY)
#  define UBXSOCKETSESSIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBXSOCKETSESSIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBXSOCKETSESSION_GLOBAL_H
